//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace ESFA.DC.Serialization.Tests.Model {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/SerializationTestsModel.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/SerializationTestsModel.xsd", IsNullable=false)]
    public partial class Root {
        
        private string stringFieldField;
        
        private RootComplexField complexFieldField;
        
        private RootCollectionField[] collectionFieldField;
        
        private string mandatoryStringFieldField;
        
        /// <remarks/>
        public string StringField {
            get {
                return this.stringFieldField;
            }
            set {
                this.stringFieldField = value;
            }
        }
        
        /// <remarks/>
        public RootComplexField ComplexField {
            get {
                return this.complexFieldField;
            }
            set {
                this.complexFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CollectionField")]
        public RootCollectionField[] CollectionField {
            get {
                return this.collectionFieldField;
            }
            set {
                this.collectionFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MandatoryStringField {
            get {
                return this.mandatoryStringFieldField;
            }
            set {
                this.mandatoryStringFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/SerializationTestsModel.xsd")]
    public partial class RootComplexField {
        
        private string stringFieldField;
        
        private string integerFieldField;
        
        /// <remarks/>
        public string StringField {
            get {
                return this.stringFieldField;
            }
            set {
                this.stringFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string IntegerField {
            get {
                return this.integerFieldField;
            }
            set {
                this.integerFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/SerializationTestsModel.xsd")]
    public partial class RootCollectionField {
        
        private string stringFieldField;
        
        private string optionalStringFieldField;
        
        private string positiveIntegerFieldField;
        
        private decimal decimalFieldField;
        
        /// <remarks/>
        public string StringField {
            get {
                return this.stringFieldField;
            }
            set {
                this.stringFieldField = value;
            }
        }
        
        /// <remarks/>
        public string OptionalStringField {
            get {
                return this.optionalStringFieldField;
            }
            set {
                this.optionalStringFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string PositiveIntegerField {
            get {
                return this.positiveIntegerFieldField;
            }
            set {
                this.positiveIntegerFieldField = value;
            }
        }
        
        /// <remarks/>
        public decimal DecimalField {
            get {
                return this.decimalFieldField;
            }
            set {
                this.decimalFieldField = value;
            }
        }
    }
}
